name: flutter_quiz
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'adrianogba'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Pub.dev dependencies
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_analytics: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


